### ISSUE TITLE
Error on install: "field_example is not a Field Collection field"

### ISSUE THREAD

**Issue by georgjaehnig** [georgjaehnig/serchilo-drupal#151]
```
Importing shortcuts...
exception 'Exception' with message 'Invalid field name given: field_example is not a Field Collection field.' in                                   [error]
/Users/jorge/data/my/code/websites/ser/drupal/sites/all/modules/field_collection/field_collection.entity.inc:101
Stack trace:
#0 /Users/jorge/data/my/code/websites/ser/drupal/sites/all/modules/entity/includes/entity.controller.inc(542):
FieldCollectionItemEntity->__construct(Array, 'field_collectio...')
#1 /Users/jorge/data/my/code/websites/ser/drupal/sites/all/modules/entity/entity.module(464): EntityAPIController->create(Array)
#2 /Users/jorge/data/my/code/websites/ser/drupal/profiles/serchilo_profile/modules/serchilo/serchilo.import.inc(130):
entity_create('field_collectio...', Array)
#3 /Users/jorge/data/my/code/websites/ser/drupal/profiles/serchilo_profile/modules/serchilo/serchilo.import.inc(31):
serchilo_import_shortcuts(Array, true)
#4 /Users/jorge/data/my/code/websites/ser/drupal/profiles/serchilo_profile/modules/serchilo/serchilo.install(12):
serchilo_import('profiles/serchi...', true)
#5 [internal function]: serchilo_install()
#6 /Users/jorge/data/my/code/websites/ser/drupal/includes/module.inc(905): call_user_func_array('serchilo_instal...', Array)
#7 /Users/jorge/data/my/code/websites/ser/drupal/includes/module.inc(477): module_invoke('serchilo', 'install')
#8 /Users/jorge/.composer/vendor/drush/drush/commands/core/drupal/environment_7.inc(143): module_enable(Array)
#9 /Users/jorge/.composer/vendor/drush/drush/commands/pm/pm.drush.inc(1120): drush_module_enable(Array)
#10 [internal function]: drush_pm_enable('serchilo')
#11 /Users/jorge/.composer/vendor/drush/drush/includes/command.inc(364): call_user_func_array('drush_pm_enable', Array)
#12 /Users/jorge/.composer/vendor/drush/drush/includes/command.inc(215): _drush_invoke_hooks(Array, Array)
#13 [internal function]: drush_command('serchilo')
#14 /Users/jorge/.composer/vendor/drush/drush/includes/command.inc(183): call_user_func_array('drush_command', Array)
#15 /Users/jorge/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(62): drush_dispatch(Array)
#16 /Users/jorge/.composer/vendor/drush/drush/drush.php(70): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#17 /Users/jorge/.composer/vendor/drush/drush/drush.php(11): drush_main()
#18 {main}
```

**Comment by georgjaehnig** [comment]
Obsolete within successor www.trovu.net.
